### ISSUE TITLE
where i can store ebooks?

### ISSUE THREAD

**Issue by Mr-V3N0M** [iam-mhaseeb/Bookly#2]
where i can store ebooks?

**Comment by iam-mhaseeb** [comment]
@Mr-V3N0M  When I started this project, I stored books in Firebase but unfortunately I lost that data. You need to build a new schema on Firebase with books and it's a database using the app's code.

**Comment by Mr-V3N0M** [comment]
okay thank you sir

**Comment by iam-mhaseeb** [comment]
@Mr-V3N0M It would helpful for others too if you can open source your data & link with the app using a pull request.
